-- =============================================================================
-- ArthSetu AI - Step 3: pgvector Extension & RAG Semantic Search Schema
-- Enables pgvector extension on Supabase PostgreSQL for 384-dim embeddings
-- (Generated by sentence-transformers all-MiniLM-L6-v2)
-- =============================================================================

-- 1. Enable pgvector extension in PostgreSQL
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Create vector storage table for verified scheme document chunks
CREATE TABLE IF NOT EXISTS scheme_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scheme_id UUID NOT NULL REFERENCES schemes(id) ON DELETE CASCADE,
    chunk_type TEXT NOT NULL, -- 'overview', 'rates', 'eligibility', 'documents', 'guidance'
    content TEXT NOT NULL,
    embedding vector(384),    -- 384-dimensional dense vectors from all-MiniLM-L6-v2
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_name TEXT NOT NULL DEFAULT 'NSFDC Official Website',
    source_url TEXT NOT NULL DEFAULT 'https://nsfdc.nic.in/scheme',
    last_verified_at DATE NOT NULL DEFAULT '2026-09-05',
    needs_manual_verification BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Create Vector Similarity Index (Cosine Distance)
CREATE INDEX IF NOT EXISTS idx_scheme_chunks_embedding
ON scheme_chunks
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 10);

-- 4. Enable Row Level Security (RLS) for public search
ALTER TABLE scheme_chunks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pub_read_scheme_chunks" ON scheme_chunks;
CREATE POLICY "pub_read_scheme_chunks" ON scheme_chunks FOR SELECT USING (true);

-- 5. Stored Procedure for Supabase RPC Vector Similarity Match
CREATE OR REPLACE FUNCTION match_scheme_chunks(
    query_embedding vector(384),
    match_threshold float DEFAULT 0.2,
    match_count int DEFAULT 4
)
RETURNS TABLE (
    id UUID,
    scheme_id UUID,
    chunk_type TEXT,
    content TEXT,
    similarity float,
    source_name TEXT,
    source_url TEXT,
    last_verified_at DATE,
    needs_manual_verification BOOLEAN
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        scheme_chunks.id,
        scheme_chunks.scheme_id,
        scheme_chunks.chunk_type,
        scheme_chunks.content,
        1 - (scheme_chunks.embedding <=> query_embedding) AS similarity,
        scheme_chunks.source_name,
        scheme_chunks.source_url,
        scheme_chunks.last_verified_at,
        scheme_chunks.needs_manual_verification
    FROM scheme_chunks
    WHERE 1 - (scheme_chunks.embedding <=> query_embedding) > match_threshold
    ORDER BY scheme_chunks.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;
