-- =============================================================================
-- ArthSetu AI — Database Schema Migration (Step 5: Partners, Applications & Documents)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Partners Table (Channelizing Agencies, Banks, MFIs)
CREATE TABLE IF NOT EXISTS partners (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    name TEXT NOT NULL,
    partner_type TEXT NOT NULL CHECK (partner_type IN ('SCA', 'PSB', 'RRB', 'NBFC_MFI', 'Cooperative')),
    address TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    pincode TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    status TEXT NOT NULL DEFAULT 'Operational' CHECK (status IN ('Operational', 'Active', 'Temporarily Inactive')),
    supported_schemes TEXT[] NOT NULL DEFAULT '{}',
    source TEXT NOT NULL DEFAULT 'NSFDC Official SCA Directory',
    last_verified_at DATE NOT NULL DEFAULT CURRENT_DATE,
    data_confidence_label TEXT NOT NULL CHECK (data_confidence_label IN ('Verified Master Data', 'Prototype/Demo Data', 'Pending Live Verification')),
    data_status TEXT NOT NULL DEFAULT 'verified',
    verification_status TEXT DEFAULT 'verified',
    verification_source_type TEXT DEFAULT 'official_directory',
    verification_notes TEXT,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    operating_hours TEXT DEFAULT '10:00 AM - 5:00 PM (Mon-Sat)',
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Partner Scheme Mapping Table
CREATE TABLE IF NOT EXISTS partner_scheme_mapping (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    partner_id TEXT NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
    scheme_id UUID NOT NULL REFERENCES schemes(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_partner_scheme UNIQUE (partner_id, scheme_id)
);

-- 3. Applications Table
CREATE TABLE IF NOT EXISTS applications (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    application_number TEXT NOT NULL UNIQUE,
    scheme_id UUID REFERENCES schemes(id),
    scheme_name TEXT NOT NULL,
    partner_id TEXT REFERENCES partners(id),
    partner_name TEXT,
    applicant_name TEXT NOT NULL,
    applicant_phone TEXT NOT NULL,
    applicant_email TEXT,
    annual_family_income NUMERIC NOT NULL,
    loan_amount NUMERIC NOT NULL,
    project_cost NUMERIC NOT NULL,
    purpose TEXT NOT NULL,
    sc_caste_declared BOOLEAN NOT NULL DEFAULT true,
    status TEXT NOT NULL DEFAULT 'Submitted' CHECK (
        status IN (
            'Draft',
            'Submitted',
            'Under Review',
            'Documents Required',
            'Forwarded to Partner',
            'Processing',
            'Decision'
        )
    ),
    decision_verdict TEXT,
    remarks TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. Application Documents Checklist & Uploads Table
CREATE TABLE IF NOT EXISTS application_documents (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    document_type TEXT NOT NULL,
    document_name TEXT NOT NULL,
    is_mandatory BOOLEAN NOT NULL DEFAULT true,
    file_url TEXT,
    is_uploaded BOOLEAN NOT NULL DEFAULT false,
    is_verified_demo BOOLEAN NOT NULL DEFAULT false,
    verification_notes TEXT,
    uploaded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5. Application Status History (Audit Timeline) Table
CREATE TABLE IF NOT EXISTS application_status_history (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    application_id UUID NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    from_status TEXT,
    to_status TEXT NOT NULL,
    remarks TEXT NOT NULL,
    updated_by TEXT NOT NULL DEFAULT 'System',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_partners_city ON partners(city);
CREATE INDEX IF NOT EXISTS idx_partners_state ON partners(state);
CREATE INDEX IF NOT EXISTS idx_partners_type ON partners(partner_type);
CREATE INDEX IF NOT EXISTS idx_partners_confidence ON partners(data_confidence_label);
CREATE INDEX IF NOT EXISTS idx_apps_number ON applications(application_number);
CREATE INDEX IF NOT EXISTS idx_apps_phone ON applications(applicant_phone);
CREATE INDEX IF NOT EXISTS idx_apps_status ON applications(status);
CREATE INDEX IF NOT EXISTS idx_app_docs_app ON application_documents(application_id);
CREATE INDEX IF NOT EXISTS idx_app_history_app ON application_status_history(application_id);

-- Row Level Security (RLS)
ALTER TABLE partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE partner_scheme_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "pub_read_partners_v5" ON partners;
DROP POLICY IF EXISTS "pub_read_partner_mapping_v5" ON partner_scheme_mapping;
DROP POLICY IF EXISTS "pub_read_apps_v5" ON applications;
DROP POLICY IF EXISTS "pub_write_apps_v5" ON applications;
DROP POLICY IF EXISTS "pub_read_docs_v5" ON application_documents;
DROP POLICY IF EXISTS "pub_write_docs_v5" ON application_documents;
DROP POLICY IF EXISTS "pub_read_history_v5" ON application_status_history;
DROP POLICY IF EXISTS "pub_write_history_v5" ON application_status_history;

CREATE POLICY "pub_read_partners_v5" ON partners FOR SELECT USING (true);
CREATE POLICY "pub_read_partner_mapping_v5" ON partner_scheme_mapping FOR SELECT USING (true);
CREATE POLICY "pub_read_apps_v5" ON applications FOR SELECT USING (true);
CREATE POLICY "pub_write_apps_v5" ON applications FOR ALL USING (true);
CREATE POLICY "pub_read_docs_v5" ON application_documents FOR ALL USING (true);
CREATE POLICY "pub_read_history_v5" ON application_status_history FOR ALL USING (true);

-- ── SEED VERIFIED REAL 38 STATE CHANNELIZING AGENCIES (SCAs) ─────────────────
-- Sourced directly from official NSFDC directory (nsfdc.nic.in/our-channel-partners)
-- Latitude/Longitude are intentionally NULL per NSFDC published data
INSERT INTO partners (
    id, name, partner_type, address, city, state, pincode,
    latitude, longitude, status, supported_schemes, source,
    last_verified_at, data_confidence_label, data_status, is_active
) VALUES
(
    'sca_ap_1',
    'Andhra Pradesh Scheduled Castes Cooperative Finance Corporation Ltd. (APSCCFC)',
    'SCA',
    'SP River View Apartments, 3rd Floor, Tadepalli, Amaravathi - 522501',
    'Amaravathi',
    'Andhra Pradesh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_ap_2',
    'Andhra Pradesh State Financial Corporation (APSFC)',
    'SCA',
    'APSFC Building, Plot OS No.2, 2nd Cross, 3rd Road, Industrial Park, Vijayawada - 520007',
    'Vijayawada',
    'Andhra Pradesh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_as_1',
    'Assam State Development Corporation for SCs Ltd. (ASCDC)',
    'SCA',
    'Swahid Dilip Hozori Path, Sarumotoria, Dispur, Guwahati - 781006',
    'Guwahati',
    'Assam',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_br_1',
    'Bihar State SCs Co-operative Development Corporation Ltd. (BSSCCDC)',
    'SCA',
    'RN-212, Officers Colony (Block-A), Bailey Road, Patna - 800001',
    'Patna',
    'Bihar',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_ch_1',
    'Chandigarh SCs, BCs & Minorities Financial & Development Corporation Ltd. (CSCFDC)',
    'SCA',
    '3rd Floor, Additional Town Hall Building, Sector-17-C, Chandigarh - 160017',
    'Chandigarh',
    'Chandigarh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_cg_1',
    'Chhattisgarh State Antavasayee Sahkari Fin. & Dev. Corpn. (CGSCFDC)',
    'SCA',
    '4th Floor, Business Complex, Chhattisgarh Housing Board Bhawan, Naya Raipur, Chhattisgarh - 492101',
    'Naya Raipur',
    'Chhattisgarh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_dnh_1',
    'Dadra & Nagar Haveli, Daman & Diu SCs/STs/OBCs & Minorities Financial & Development Corporation (DNDSFDC)',
    'SCA',
    'Ground Floor, Right Wing, New Collectorate Building, Near Electricity Department, Silvassa - 396230',
    'Silvassa',
    'Dadra & Nagar Haveli, Daman & Diu',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_dl_1',
    'Delhi SC/ST/OBC/Minorities & Handicapped Financial & Development Corporation (DSFDC)',
    'SCA',
    'Ambedkar Bhawan, Sector-16 (Opp. Sector-11), Rohini, Delhi - 110085',
    'Delhi',
    'Delhi',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_gj_1',
    'Gujarat SCs Development Corporation (GSCDC)',
    'SCA',
    'Dr Jivraj Mehta Bhawan, Block - 10, II Floor, Old Sachivalaya, Gandhinagar - 382010',
    'Gandhinagar',
    'Gujarat',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_gj_2',
    'Dr. Ambedkar Antyodaya Vikas Nigam (S.C.) (DAAVN)',
    'SCA',
    'Karmayogi Bhavan, Block No. 2, D-2 Wing, 4th Floor, Sector-10/B, Gandhinagar',
    'Gandhinagar',
    'Gujarat',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_ga_1',
    'Goa State SCs & OBCs Finance and Development Corporation Ltd. (GSCOBCDC)',
    'SCA',
    '4th Floor, Patto Centre, Near K.T.C. Bus Stand, Panaji, Goa - 403001',
    'Panaji',
    'Goa',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_hr_1',
    'Haryana SCs Fin. and Development Corporation Ltd. (HSCDC)',
    'SCA',
    'SCO-2427-28, Sector 22-C, Chandigarh - 160022',
    'Chandigarh',
    'Haryana',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_hp_1',
    'Himachal Pradesh SCs & STs Development Corporation (HPSCSTDC)',
    'SCA',
    'Kalyan Bhawan, Near Ambusha Resort, Solan - 173212',
    'Solan',
    'Himachal Pradesh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_jh_1',
    'Jharkhand State Scheduled Castes Cooperative Development Corporation (JSCDC)',
    'SCA',
    'Kalyan Complex, 3rd Floor, Balihar Road, Morabadi, Ranchi - 834008',
    'Ranchi',
    'Jharkhand',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_jk_1',
    'J&K SCs, STs & OBCs Dev. Corpn. Ltd. (JKSCSTBCDC)',
    'SCA',
    'Exchange Road, Near Red Cross Office, Srinagar - 190001 (May-Oct); 135-A, Last Morh, Gandhi Nagar, Jammu - 180004 (Nov-Apr)',
    'Srinagar',
    'Jammu & Kashmir',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_ka_1',
    'Dr B. R. Ambedkar Development Corporation Ltd. (DBRADC)',
    'SCA',
    '9th & 10th Floor, Visheshwariah Mini Tower, Dr Ambedkar Veedhi, Bengaluru - 560001',
    'Bengaluru',
    'Karnataka',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_kl_1',
    'Kerala State Development Corporation for SCs & STs Ltd. (KSDC)',
    'SCA',
    'Town Hall Road, Thrissur - 680020',
    'Thrissur',
    'Kerala',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_kl_2',
    'Kerala State Women''s Development Corporation (KSWDC)',
    'SCA',
    '1st Floor, Transport Bhavan, KSRTC Building, East Fort, Attakulangara - 695023',
    'Thiruvananthapuram',
    'Kerala',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mp_1',
    'MP State Cooperative SC Finance & Development Corporation (MPSCFDC)',
    'SCA',
    'Rajiv Gandhi Bhawan, 35, Shyamala Hills, Bhopal - 462011',
    'Bhopal',
    'Madhya Pradesh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mh_1',
    'Mahatma Phule BCs Development Corporation Ltd. (MPBCDC)',
    'SCA',
    '1-N, Supreme Shopping Centre, Gulmohar Cross Road No.9, J.V.P.D. Scheme, Juhu, Mumbai - 400049',
    'Mumbai',
    'Maharashtra',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mh_2',
    'Sahityaratna Lokshahir Annabhau Sathe Development Corporation Ltd. (SLASDC)',
    'SCA',
    'New Administration Building No.2, 3rd Floor, Ramkrushna Chemburkar Marg, Chembur (E), Mumbai - 400071',
    'Mumbai',
    'Maharashtra',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mh_3',
    'Sant Rohidas Leather Industries & Charmakar Development Corporation (LIDCOM)',
    'SCA',
    'Bombay Life Building, 5th Floor, 45, Veer Nariman Road, Mumbai - 400001',
    'Mumbai',
    'Maharashtra',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mn_1',
    'Manipur Tribal Development Corporation Ltd. (MTDC)',
    'SCA',
    'Lamphelpat, Imphal - 795004',
    'Imphal',
    'Manipur',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mn_2',
    'Manipur SCs & STs Cooperative Dev. Bank (MSTCB)',
    'SCA',
    'Nambun Long, Stadium Road, Imphal East, Manipur - 795001',
    'Imphal',
    'Manipur',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_ml_1',
    'Meghalaya Cooperative Apex Bank Ltd. (MCAB)',
    'SCA',
    'M.G. Road, Kutchery, Shillong - 793001',
    'Shillong',
    'Meghalaya',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mz_1',
    'Mizoram Urban Cooperative Development Bank Ltd. (MUCO Bank)',
    'SCA',
    'Lawlsawmiliani Building (Top Floor), Zarkawt, Aizawl - 796001',
    'Aizawl',
    'Mizoram',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_mz_2',
    'Mizoram Khadi & Village Industries Board (MKVIB)',
    'SCA',
    '''Zorun'', Zarkawt, Aizawl - 796007',
    'Aizawl',
    'Mizoram',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_or_1',
    'Odisha SCs & STs Dev. Finance Co-op. Corpn. Ltd. (OSFDC)',
    'SCA',
    'Lewis Road, Bhubaneswar - 751014',
    'Bhubaneswar',
    'Odisha',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_py_1',
    'Puducherry Adi Dravidar Dev. Corpn. Ltd. (PADCO)',
    'SCA',
    'III Floor, Directorate of Adi Dravidar Welfare Department, Thattanchavady, Puducherry - 605009',
    'Puducherry',
    'Puducherry',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_pb_1',
    'Punjab Scheduled Castes Land Development & Finance Corporation (PSCLDFC)',
    'SCA',
    'SCO No.101-102-103, Sector 17-C, Chandigarh - 160017',
    'Chandigarh',
    'Punjab',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_rj_1',
    'Rajasthan SCs & STs Fin. & Dev. Co-op. Corporation Ltd. (RSCDC)',
    'SCA',
    'III Floor, Central Block, Nehru Sahakar Bhawan, Bhawani Singh Marg, Jaipur - 302005',
    'Jaipur',
    'Rajasthan',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_sk_1',
    'Sikkim SCs, STs & Backward Classes Development Corporation (SSCSTBCDC)',
    'SCA',
    'Bhanupath, Gangtok, Sikkim - 737101',
    'Gangtok',
    'Sikkim',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_tn_1',
    'Tamil Nadu Adi Dravidar Housing & Development Corporation Ltd. (TAHDCO)',
    'SCA',
    'No.31, Cenotaph Road, 2nd Lane, Teynampet, Chennai - 600018',
    'Chennai',
    'Tamil Nadu',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_tr_1',
    'Tripura Scheduled Castes Co-op. Devp. Corpn. Ltd. (TSCDC)',
    'SCA',
    'Krishna Nagar P.O., Lake Chomubani, Agartala - 799001',
    'Agartala',
    'Tripura',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_uk_1',
    'Uttarakhand Bahu-udeshiya Vitta Evam Vikas Nigam (UBVEVN)',
    'SCA',
    'Janjati Directorate, New Building, Bhagat Singh Colony (Adhoiwala), Dehradun - 248001',
    'Dehradun',
    'Uttarakhand',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_up_1',
    'UP Sahkari Gram Vikas Bank Ltd.',
    'SCA',
    '10, Mall Avenue, Lucknow, Uttar Pradesh - 226001',
    'Lucknow',
    'Uttar Pradesh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_up_2',
    'UP Scheduled Castes Finance & Dev. Corpn. Ltd. (UPSCFDC)',
    'SCA',
    'B-912, Sector-C, Mahanagar, Lucknow - 226006',
    'Lucknow',
    'Uttar Pradesh',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
),
(
    'sca_wb_1',
    'West Bengal SCs, STs & OBC Development & Finance Corporation (WBSCSTOBCDFC)',
    'SCA',
    'CF 217/A/1, Salt Lake Sector-I (Mangolic Building), Kolkata - 700064',
    'Kolkata',
    'West Bengal',
    NULL,
    NULL,
    NULL,
    'Operational',
    ARRAY['micro_finance', 'term_loan', 'education_loan', 'micro_finance_mfi'],
    'NSFDC Official SCA Directory (nsfdc.nic.in/our-channel-partners)',
    '2026-09-04',
    'Verified Master Data',
    'verified',
    true
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    status = EXCLUDED.status,
    supported_schemes = EXCLUDED.supported_schemes,
    last_verified_at = EXCLUDED.last_verified_at,
    data_confidence_label = EXCLUDED.data_confidence_label,
    data_status = EXCLUDED.data_status,
    updated_at = now();
